# Generated by Django 3.2.5 on 2021-07-18 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov ankete')),
                ('description', models.TextField(verbose_name='Opis ankete')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Datum objavljivanja')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Anketa',
                'verbose_name_plural': 'Ankete',
                'ordering': ['pub_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Tekst pitanja')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll', verbose_name='Anketa')),
            ],
            options={
                'verbose_name': 'Pitanje',
                'verbose_name_plural': 'Pitanja',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Tekst opcije')),
                ('votes', models.IntegerField(default=0, verbose_name='Glasovi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question', verbose_name='Pitanje')),
            ],
            options={
                'verbose_name': 'Opcija',
                'verbose_name_plural': 'Opcije',
            },
        ),
    ]
